export const ROOM_CAMERA_SLOT_OVERRIDES = {
  SLOT_LAMP: "CAM_SOFA_TABLE_LAMP",
  SLOT_TABLE: "CAM_SOFA_TABLE_LAMP",
  SLOT_CARPET: "CAM_SOFA_TABLE_LAMP",
  SLOT_SOFA: "CAM_SOFA_TABLE_LAMP",
} as const;
