export const ROOM_CAMERA_SLOT_OVERRIDES = {
  SLOT_LAMP: "CAM_LIVING",
  SLOT_TABLE: "CAM_LIVING",
  SLOT_CARPET: "CAM_LIVING",
  SLOT_SOFA: "CAM_LIVING",
  SLOT_TABLE_KITCHEN: "CAM_KITCHEN",
  SLOT_CABINET_KITCHEN: "CAM_KITCHEN",
  SLOT_SHELF_KITCHEN: "CAM_SHELF_KITCHEN",
} as const;
